# Generated by Django 4.2.28 on 2026-02-15 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_worklog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("message", models.TextField(blank=True, verbose_name="Mesaj")),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Yönlendirme URL"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Bilgi"),
                            ("success", "Başarılı"),
                            ("warning", "Uyarı"),
                            ("danger", "Kritik"),
                        ],
                        default="info",
                        max_length=10,
                        verbose_name="Seviye",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Okundu mu?"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İşlemi Yapan",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Alıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirim",
                "verbose_name_plural": "Bildirimler",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="core_notifi_recipie_1d5476_idx",
                    )
                ],
            },
        ),
    ]
