# Generated by Django 4.2.28 on 2026-02-15 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="core.task",
                verbose_name="İlgili Görev",
            ),
        ),
    ]
