# Generated by Django 4.2.28 on 2026-02-16 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_notification_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmapitem",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Tamamlanma Zamanı"
            ),
        ),
        migrations.AddField(
            model_name="roadmapitem",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_roadmap_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Tamamlayan",
            ),
        ),
    ]
